package com.cardplatform.common.exception;

public enum ErrorCode {

    INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR"),
    VALIDATION_ERROR("VALIDATION_ERROR"),
    MALFORMED_REQUEST("MALFORMED_REQUEST"),
    RESOURCE_NOT_FOUND("RESOURCE_NOT_FOUND"),
    BAD_REQUEST("BAD_REQUEST"),
    CONFLICT("CONFLICT"),
    DOMAIN_ERROR("DOMAIN_ERROR"),
    BUSINESS_RULE_VIOLATION("BUSINESS_RULE_VIOLATION"),
    INSUFFICIENT_FUNDS("INSUFFICIENT_FUNDS"),
    CARD_INACTIVE("CARD_INACTIVE"),
    CARD_LIMIT_EXCEEDED("CARD_LIMIT_EXCEEDED"),
    TRANSACTION_NOT_PERMITTED("TRANSACTION_NOT_PERMITTED"),
    LEDGER_UNBALANCED("LEDGER_UNBALANCED"),
    IDEMPOTENCY_KEY_MISSING("IDEMPOTENCY_KEY_MISSING"),
    IDEMPOTENCY_CONFLICT("IDEMPOTENCY_CONFLICT"),
    IDEMPOTENCY_PROCESSING("IDEMPOTENCY_PROCESSING");

    private final String value;

    ErrorCode(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }
}
